[package]
name = "jingle_sleigh"
version = "0.1.1"
edition = "2021"
description = "An FFI layer for Ghidra's SLEIGH"
homepage = "https://github.com/toolCHAINZ/jingle"
repository = "https://github.com/toolCHAINZ/jingle"
readme = "README.md"
license = "MIT"
authors = ["toolCHAINZ"]
rust-version = "1.77.0"
categories = ["api-bindings"]
keywords = ["ghidra", "sleigh", "pcode"]
include = [
    "Cargo.toml",
    "SLEIGH_LICENSE",
    "build.rs",
    "src/**/*.*"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.122"
serde = { version = "1.0.203", features = ["derive"] }
serde-xml-rs = "0.6.0"
thiserror = { version = "1.0.61", features = [] }
object = { version = "0.36.0", optional = true }
libz-sys = { version = "1.1.18", default-features = false, features = ["libc"] }
tracing = "0.1.40"
vfs = { version = "0.12.0", features = ["embedded-fs"] }
rust-embed = "8.0.0"

[build-dependencies]
cxx-build = "1.0.122"

[features]
gimli = ["dep:object"]
default = ["gimli"]


